# https://editor.swagger.io/
openapi: 3.0.0
info:
  title: ECommerce API
  description: Optional multiline or single-line description in HTML.
  version: 0.1.9
servers:
  - url: https://allendc630.local:30008/
    description: Optional server description, e.g. Main (production) server
  - url:  https://localhost:3000/
    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: currency-controller
    description: Controller which manages all endpoints related to currency controller
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /currency/list:
    get:
      tags:
        - currency-controller
      summary: Returns a list of currencies available.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /currency/convert:
    get:
      tags:
        - currency-controller
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string